### ISSUE TITLE
Lead-acid battery Prognostic Model?

### ISSUE THREAD

**Issue by hacmachdien** [nasa/PrognosticsModelLibrary#4]
Hi,

I'm researching Prognostic Modeling for stationary Lead-acid battery with the ultimate purpose of battery aging prediction. Can I take the provided li-on model and adapt its parameters to a Lead-acid one?

**Comment by matthewjdaigle** [comment]
To some extent, yes. The electrochemistry equations are general and apply to different chemistries, but are characterized with different parameters. There is one simplification to the Butler-Volmer equation here which applies in the case of Li-ion; I am not sure if it applies also to lead-acid but it might be a sufficient approximation for that case. So far we have only tried this model with Li-ion and Li polymer chemistries.

If open-circuit discharge data is available (or discharge data at something like C/100), then I would suggest first to estimate the parameters associated with the Redlich-Kister expansion (in this case we assume no voltage contributions from the other processes, so you can ignore their parameters). Once that is done, you can then estimate remaining parameters using normal discharge data.
